import React from "react";
import type { ColumnsType } from "antd/es/table";
import {
  ListTask,
  ListItem,
  ListUser,
  ListPlatform,
  ListAudit,
} from "../../types/baseTypes";
import {
  shortenAddress,
  bignumberConvert,
  shortenText,
  timestampToDate,
} from "../tools";
import { DECIMALS_18 } from "../constants";

export const columns: {
  [key: string]: ColumnsType<
    ListTask | ListItem | ListUser | ListPlatform | ListAudit
  >;
} = {
  Tasks: [
    {
      title: "ID",
      dataIndex: "id",
      key: "id",
      fixed: "left",
      width: "100px",
      render: (text) => `#${text}`,
    },
    {
      title: "Reuire",
      dataIndex: "require",
      key: "require",
    },
    {
      title: "Payment",
      dataIndex: "payment",
      key: "payment",
      width: "100px",
    },
    {
      title: "Currency",
      dataIndex: "currency",
      key: "currency",
      width: "120px",
    },
    {
      title: "Amount",
      key: "amount",
      dataIndex: "amount",
      width: "150px",
      render: (text) => shortenText(text, 6),
    },
    {
      title: "Audit",
      key: "audit",
      dataIndex: "audit",
      width: "150px",
      render: (text) => shortenAddress(text),
    },
    {
      title: "Detection",
      key: "detection",
      dataIndex: "detection",
      width: "150px",
      render: (text) => shortenAddress(text),
    },
    {
      title: "State",
      key: "state",
      dataIndex: "state",
      width: "200px",
    },
  ],
  Items: [
    {
      title: "ID",
      dataIndex: "id",
      key: "id",
      fixed: "left",
      width: "100px",
      render: (text) => `#${text}`,
    },
    {
      title: "Task ID",
      dataIndex: "task",
      key: "task",
      width: "100px",
      render: (text) => `#${text}`,
    },
    {
      title: "Require",
      dataIndex: "require",
      key: "require",
    },
    {
      title: "Support",
      dataIndex: "support",
      key: "support",
      width: "100px",
    },
    {
      title: "Oppose",
      dataIndex: "oppose",
      key: "oppose",
      width: "100px",
    },
    {
      title: "State",
      dataIndex: "state",
      key: "state",
      width: "100px",
    },
    {
      title: "Source",
      dataIndex: "source",
      key: "source",
      width: "200px",
      render: (text) => shortenText(text, 6),
    },
    {
      title: "Fingerprint",
      dataIndex: "fingerprint",
      key: "fingerprint",
      width: "200px",
      render: (text) => shortenText(text, 6),
    },
  ],
  Users: [
    {
      title: "ID",
      dataIndex: "id",
      key: "id",
      fixed: "left",
      width: "100px",
      render: (text) => `#${text}`,
    },
    {
      title: "Address",
      dataIndex: "address",
      key: "address",
      render: (text) => shortenAddress(text),
    },
    {
      title: "Reputation",
      dataIndex: "reputation",
      key: "reputation",
      width: "150px",
      render: (text) => bignumberConvert(text, 10, 1),
    },
    {
      title: "Deposit",
      dataIndex: "deposit",
      key: "deposit",
      width: "150px",
      render: (text) => bignumberConvert(text, DECIMALS_18, 2),
    },
    {
      title: "Post Tasks",
      dataIndex: "tasks",
      key: "tasks",
    },
    {
      title: "Submit Items",
      dataIndex: "items",
      key: "items",
    },
    {
      title: "Audit Items",
      dataIndex: "audits",
      key: "audits",
    },
    {
      title: "Guard",
      dataIndex: "guard",
      key: "guard",
      width: "150px",
      render: (text) => shortenAddress(text),
    },
  ],
  Platforms: [
    {
      title: "ID",
      dataIndex: "id",
      key: "id",
      fixed: "left",
      width: "100px",
      render: (text) => `#${text}`,
    },
    {
      title: "Name",
      dataIndex: "name",
      key: "name",
    },
    {
      title: "Admin",
      dataIndex: "owner",
      key: "owner",
      width: "150px",
      render: (text) => shortenAddress(text),
    },
    {
      title: "Authority",
      dataIndex: "authority",
      key: "authority",
      width: "150px",
      render: (text) => shortenAddress(text),
    },
    {
      title: "Earnings Rate",
      dataIndex: "rate1",
      key: "rate1",
      render: (text) => parseInt(text) / 100 + "%",
    },
    {
      title: "Share Rate",
      dataIndex: "rate2",
      key: "rate2",
      render: (text) => parseInt(text) / 100 + "%",
    },
    {
      title: "Boxes",
      dataIndex: "boxes",
      key: "boxes",
      width: "100px",
    },
  ],
  Audits: [
    {
      title: "ID",
      dataIndex: "id",
      key: "id",
      width: "100px",
      render: (text) => `#${text}`,
    },
    {
      title: "Auditor",
      dataIndex: "auditor",
      key: "auditor",
      width: "150px",
      render: (text) => shortenAddress(text),
    },
    {
      title: "Reputation",
      dataIndex: "reputation",
      key: "reputation",
      width: "100px",
      render: (text) => bignumberConvert(text, 10, 1),
    },
    {
      title: "Result",
      dataIndex: "result",
      key: "result",
      width: "100px",
    },
    {
      title: "Time",
      dataIndex: "time",
      key: "time",
      width: "150px",
      render: (text) => timestampToDate(text),
    },
  ],
};

export const data: ListTask[] = [
  {
    key: "1",
    id: "1",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
  {
    key: "2",
    id: "2",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
  {
    key: "3",
    id: "3",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
  {
    key: "4",
    id: "4",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
  {
    key: "5",
    id: "5",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
  {
    key: "6",
    id: "6",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
  {
    key: "7",
    id: "7",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
  {
    key: "8",
    id: "8",
    require: "Translate",
    payment: "OT0",
    currency: "USDT",
    amount: "20.0",
    audit: "0x111.222",
    detection: "0x111.222",
    state: "Normal",
  },
];
